version: '3'
services:
  app:
    build: . 
    container_name: "app"
    command: ["go", "run", "main.go"]
    ports:
      - "10000:10000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NEO
      PGDATA: /var/lib/postgresql/data/neo/
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped      

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data: